/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regex.view;

/**
 *
 * @author MarkZamudio
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        jbnAnalizeInputs.setOpaque(false);
        jbnShowReport.setOpaque(false);
        jbnReadInputs.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnFill = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jlbRegExp = new javax.swing.JLabel();
        jbnReadInputs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbData = new javax.swing.JTable();
        jbnAnalizeInputs = new javax.swing.JButton();
        jbnShowReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnFill.setBackground(new java.awt.Color(255, 255, 255));
        jpnFill.setForeground(new java.awt.Color(255, 255, 255));

        jlbTitle.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jlbTitle.setText("REGEX");

        jlbRegExp.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbRegExp.setForeground(new java.awt.Color(102, 102, 102));
        jlbRegExp.setText("ER = (@@)|(@@@@)[aeiouAEIOU]{2}[#&]{2}[0-9]$");

        jbnReadInputs.setBackground(new java.awt.Color(255, 255, 255));
        jbnReadInputs.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbnReadInputs.setForeground(new java.awt.Color(68, 68, 68));
        jbnReadInputs.setText("IN");

        jtbData.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtbData.setForeground(new java.awt.Color(68, 68, 68));
        jtbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cadenas", "Resultado"
            }
        ));
        jScrollPane1.setViewportView(jtbData);

        jbnAnalizeInputs.setBackground(new java.awt.Color(255, 255, 255));
        jbnAnalizeInputs.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbnAnalizeInputs.setForeground(new java.awt.Color(68, 68, 68));
        jbnAnalizeInputs.setText("Analizar");
        jbnAnalizeInputs.setEnabled(false);

        jbnShowReport.setBackground(new java.awt.Color(255, 255, 255));
        jbnShowReport.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbnShowReport.setForeground(new java.awt.Color(68, 68, 68));
        jbnShowReport.setText("Reporte");
        jbnShowReport.setEnabled(false);

        javax.swing.GroupLayout jpnFillLayout = new javax.swing.GroupLayout(jpnFill);
        jpnFill.setLayout(jpnFillLayout);
        jpnFillLayout.setHorizontalGroup(
            jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFillLayout.createSequentialGroup()
                .addGroup(jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnFillLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jlbTitle))
                    .addGroup(jpnFillLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnFillLayout.createSequentialGroup()
                                .addComponent(jbnAnalizeInputs, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbnShowReport, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnFillLayout.createSequentialGroup()
                                .addComponent(jlbRegExp)
                                .addGap(143, 143, 143)
                                .addComponent(jbnReadInputs, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jpnFillLayout.setVerticalGroup(
            jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFillLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jlbTitle)
                .addGap(35, 35, 35)
                .addGroup(jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnReadInputs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbRegExp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnAnalizeInputs, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbnShowReport, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbnAnalizeInputs;
    public javax.swing.JButton jbnReadInputs;
    public javax.swing.JButton jbnShowReport;
    private javax.swing.JLabel jlbRegExp;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPanel jpnFill;
    public javax.swing.JTable jtbData;
    // End of variables declaration//GEN-END:variables
}
