/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regex.view;

/**
 *
 * @author MarkMVCX
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnFill = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jlbRegExp = new javax.swing.JLabel();
        btnReadInputs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbData = new javax.swing.JTable();
        jbnAnalizeInputs = new javax.swing.JButton();
        jbnShowReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbTitle.setText("REGEX");

        jlbRegExp.setText("jLabel2");

        btnReadInputs.setText("IN");

        jtbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cadena", "Resultado"
            }
        ));
        jScrollPane1.setViewportView(jtbData);

        jbnAnalizeInputs.setText("Analizar");

        jbnShowReport.setText("Reporte");

        javax.swing.GroupLayout jpnFillLayout = new javax.swing.GroupLayout(jpnFill);
        jpnFill.setLayout(jpnFillLayout);
        jpnFillLayout.setHorizontalGroup(
            jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFillLayout.createSequentialGroup()
                .addGroup(jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnFillLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbRegExp)
                            .addComponent(jlbTitle)))
                    .addGroup(jpnFillLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnReadInputs)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnFillLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jbnAnalizeInputs)
                        .addGap(129, 129, 129)
                        .addComponent(jbnShowReport)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jpnFillLayout.setVerticalGroup(
            jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFillLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jlbTitle)
                .addGap(32, 32, 32)
                .addComponent(jlbRegExp)
                .addGroup(jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnFillLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnReadInputs))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnFillLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jpnFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnAnalizeInputs)
                    .addComponent(jbnShowReport))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnReadInputs;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbnAnalizeInputs;
    public javax.swing.JButton jbnShowReport;
    private javax.swing.JLabel jlbRegExp;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JPanel jpnFill;
    public javax.swing.JTable jtbData;
    // End of variables declaration//GEN-END:variables
}
